name: sit-run-test


on:
  push:
    branches:
      -master
  pull_request:
    types: [ opened,synchronize,reopened ]
    workflow_dispatch: #To manually trigger
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      timeout-minutes: 30
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn test -B package --file pom.xml