name: sit-run-test


on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - master
  pull_request:
    types: [ opened,synchronize,reopened ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 20g
      timeout-minutes: 30
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - run: mvn clean test -Psystem-tests